# Generated by Django 5.1.7 on 2025-05-09 00:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='profile',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='main.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='withdraw_blocked',
            field=models.BooleanField(default=False, help_text='If enabled, the user will not be able to create withdrawal requests.', verbose_name='Withdrawal block'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='fail_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='first_try_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='case',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Old (strikethrough) price if discounted', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='casesection',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Section Name'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_items_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Items Value (USD)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='used_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Used Balance (USD)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='market_hash_name',
            field=models.CharField(blank=True, help_text='Unique item name for API', max_length=255, null=True, verbose_name='Market Hash Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='main.rarity', verbose_name='Rarity'),
        ),
        migrations.AlterField(
            model_name='item',
            name='skin_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Skin Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='weapon_name',
            field=models.CharField(max_length=100, verbose_name='Weapon Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Balance (USD)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='steam_avatar',
            field=models.URLField(blank=True, help_text='Steam avatar URL', null=True),
        ),
        migrations.AlterField(
            model_name='rarity',
            name='color',
            field=models.CharField(default='#ffffff', help_text='HEX color, e.g. #FF9800', max_length=7),
        ),
        migrations.AlterField(
            model_name='rarity',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Rarity Name'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='custom_id',
            field=models.CharField(default='1', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='offer_id',
            field=models.CharField(blank=True, default='0', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
